# Generated by Django 6.0.5 on 2026-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.FileField(upload_to='static/images/'),
        ),
    ]
