# Generated by Django 6.0.5 on 2026-05-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.FileField(upload_to='images/'),
        ),
    ]
